2023-12-09 02:08:22.566593: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2023-12-09 02:08:31.134141: E tensorflow/core/kernels/check_numerics_op.cc:292] abnormal_detected_host @0x7f7416e00100 = {0, 1} Bad!
Traceback (most recent call last):
  File "/home/saurabh/method-energy-dataset/projects/tensorflow_docs_patched/site/en/guide/graph_optimization_method-level.py", line 75, in <module>
    test_func(p1)
  File "/home/saurabh/miniconda3/envs/tf2/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Bad! : Tensor had Inf values
	 [[node CheckNumerics
 (defined at /home/saurabh/method-energy-dataset/projects/tensorflow_docs_patched/site/en/guide/graph_optimization_method-level.py:66)
]] [Op:__inference_simple_func_131]

Errors may have originated from an input operation.
Input Source operations connected to node CheckNumerics:
In[0] input_arg (defined at /home/saurabh/method-energy-dataset/projects/tensorflow_docs_patched/site/en/guide/graph_optimization_method-level.py:75)

Operation defined at: (most recent call last)
>>>   File "/home/saurabh/method-energy-dataset/projects/tensorflow_docs_patched/site/en/guide/graph_optimization_method-level.py", line 75, in <module>
>>>     test_func(p1)
>>> 
>>>   File "/home/saurabh/method-energy-dataset/projects/tensorflow_docs_patched/site/en/guide/graph_optimization_method-level.py", line 66, in simple_func
>>>     tf.debugging.check_numerics(output, 'Bad!')
>>> 
{'constant_folding': False, 'disable_model_pruning': False, 'disable_meta_optimizer': False}
Tracing!
Vanilla execution: 0.0024812460178509355 s
{'constant_folding': True, 'disable_model_pruning': False, 'disable_meta_optimizer': False}
Tracing!
Constant folded execution: 0.000511047022882849 s
